FROM oven/bun

WORKDIR /usr/src/app

COPY api/bun.lockb . 
COPY api/package.json . 

RUN bun install --frozen-lockfile --production

USER bun
EXPOSE 3000/tcp

ENTRYPOINT [ "bun" ]
CMD [ "run", "index.ts" ]